[platformio]
src_dir = .
include_dir = .


[env:release]
platform = ststm32
upload_protocol = stlink
monitor_speed = 115200

board = disco_f334c8 
board_build.ldscript = STM32C092XX_FLASH.ld 
extra_scripts = pre:scripts/build_flags.py
build_flags = 
    -DUSE_HAL_DRIVER
    -DSTM32C092xx
    -ICore/Inc
    -IDrivers/STM32C0xx_HAL_Driver/Inc
    -IDrivers/STM32C0xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Include
    -IDrivers/CMSIS/Device/ST/STM32C0xx/Include

build_src_filter = 
    +<*.s>
    +<Core/Src>
    +<Drivers/STM32C0xx_HAL_Driver/Src>
    -<Drivers/STM32C0xx_HAL_Driver/Src/*_template.c>
