[platformio]
src_dir = .
include_dir = .
default_envs = release


[env:release]
platform = ststm32
upload_protocol = stlink
debug_tool = stlink
platform_packages = 
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200

board = disco_f334c8 
board_build.ldscript = STM32C092XX_FLASH.ld 
extra_scripts = pre:scripts/build_flags.py
build_flags = 
    -std=gnu23
    -DUSE_HAL_DRIVER
    -DSTM32C092xx
    -ICore/Inc
    -IDrivers/STM32C0xx_HAL_Driver/Inc
    -IDrivers/STM32C0xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Include
    -IDrivers/CMSIS/Device/ST/STM32C0xx/Include

build_src_filter = 
    +<*.s>
    +<Core/Src>
    +<Drivers/STM32C0xx_HAL_Driver/Src>
    -<Drivers/STM32C0xx_HAL_Driver/Src/*_template.c>
lib_deps =

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*,-bugprone-easily-swappable-parameters
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false
check_src_filters =
    -<**>
    +<Core/Src/**>
    +<Core/Inc/**>

