/******************************************************************************
Finite State Machine
Project: lcu-sw
Description: lcu_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2026-06-24 17:40:22 +0200
Generated from: assets/fsm.dot
The finite state machine has:
  4 states
  6 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#include "fsm.h"

/*** USER CODE BEGIN MACROS ***/
#include "brake_api.h"
#include "eagletrt-api.h"
/*** USER CODE END MACROS ***/

// GLOBALS
// State human-readable names
const char *fsm_state_names[] = { "init", "idle", "fatal", "flash" };

// List of state functions
fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES] = {
    fsm_do_init,  // in state init
    fsm_do_idle,  // in state idle
    fsm_do_fatal, // in state fatal
    fsm_do_flash, // in state flash
};

// Table of transition functions
transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES] = {
    /* states:     init              , idle              , fatal             , flash              */
    /* init    */ { NULL, fsm_init_to_idle, fsm_init_to_fatal, NULL },
    /* idle    */ { NULL, NULL, fsm_idle_to_fatal, fsm_idle_to_flash },
    /* fatal   */ { NULL, NULL, NULL, NULL },
    /* flash   */ { NULL, fsm_flash_to_idle, fsm_flash_to_fatal, NULL },
};

// Triggered event
fsm_event_data_t *fsm_fired_event = NULL;

/*** USER CODE BEGIN GLOBALS ***/

/*** USER CODE END GLOBALS ***/

// Function to check if an event has fired
bool fsm_is_event_triggered() {
    return fsm_fired_event != NULL;
}

// Function to trigger an event
void fsm_event_trigger(fsm_event_data_t *event) {
    if (fsm_fired_event != NULL)
        return;
    fsm_fired_event = event ? event : &(fsm_event_data_t){};
}

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: FSM_STATE_IDLE, FSM_STATE_FATAL
fsm_state_t fsm_do_init(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_IDLE;

    /*** USER CODE BEGIN DO_INIT ***/
    struct BrakeApiHandler *init_data = (struct BrakeApiHandler *)data;
    //TODO: move this to the post module
    if (brake_api_init(init_data) != BRAKE_RC_OK) {
        next_state = FSM_STATE_FATAL;
    }
    /*** USER CODE END DO_INIT ***/

    switch (next_state) {
        case FSM_STATE_IDLE:
        case FSM_STATE_FATAL:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_FLASH, FSM_STATE_IDLE, FSM_STATE_FATAL
fsm_state_t fsm_do_idle(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_IDLE ***/
    EAGLETRT_API_UNUSED(data);
    bool pedal_dummy_status = true;
    if (pedal_dummy_status != brake_api_get_status()) {
        brake_api_set_status(pedal_dummy_status);
    }
    /*** USER CODE END DO_IDLE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_FLASH:
        case FSM_STATE_IDLE:
        case FSM_STATE_FATAL:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state fatal
// valid return states: FSM_NO_CHANGE, FSM_STATE_FLASH, FSM_STATE_FATAL
fsm_state_t fsm_do_fatal(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_FATAL ***/
    EAGLETRT_API_UNUSED(data);
    /*** USER CODE END DO_FATAL ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_FLASH:
        case FSM_STATE_FATAL:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: FSM_STATE_IDLE, FSM_STATE_FATAL
fsm_state_t fsm_do_flash(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_IDLE;

    /*** USER CODE BEGIN DO_FLASH ***/
    EAGLETRT_API_UNUSED(data);
    /*** USER CODE END DO_FLASH ***/

    switch (next_state) {
        case FSM_STATE_IDLE:
        case FSM_STATE_FATAL:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from init to idle
void fsm_init_to_idle(fsm_state_data_t *data) {

    /*** USER CODE BEGIN INIT_TO_IDLE ***/
    EAGLETRT_API_UNUSED(data);
    /*** USER CODE END INIT_TO_IDLE ***/
}

// This function is called in 1 transition:
// 1. from init to fatal
void fsm_init_to_fatal(fsm_state_data_t *data) {

    /*** USER CODE BEGIN INIT_TO_FATAL ***/
    EAGLETRT_API_UNUSED(data);
    /*** USER CODE END INIT_TO_FATAL ***/
}

// This function is called in 1 transition:
// 1. from flash to idle
void fsm_flash_to_idle(fsm_state_data_t *data) {

    /*** USER CODE BEGIN FLASH_TO_IDLE ***/
    EAGLETRT_API_UNUSED(data);
    /*** USER CODE END FLASH_TO_IDLE ***/
}

// This function is called in 1 transition:
// 1. from flash to fatal
void fsm_flash_to_fatal(fsm_state_data_t *data) {

    /*** USER CODE BEGIN FLASH_TO_FATAL ***/
    EAGLETRT_API_UNUSED(data);
    /*** USER CODE END FLASH_TO_FATAL ***/
}

// This function is called in 1 transition:
// 1. from idle to flash
void fsm_idle_to_flash(fsm_state_data_t *data) {

    /*** USER CODE BEGIN IDLE_TO_FLASH ***/
    EAGLETRT_API_UNUSED(data);
    /*** USER CODE END IDLE_TO_FLASH ***/
}

// This function is called in 1 transition:
// 1. from idle to fatal
void fsm_idle_to_fatal(fsm_state_data_t *data) {

    /*** USER CODE BEGIN IDLE_TO_FATAL ***/
    EAGLETRT_API_UNUSED(data);
    /*** USER CODE END IDLE_TO_FATAL ***/
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data) {

    /*** USER CODE BEGIN RUN_STATE ***/

    /*** USER CODE END RUN_STATE ***/

    fsm_event_data_t *prev_ev = fsm_fired_event;
    fsm_state_t new_state = fsm_state_table[cur_state](data);
    // Reset event status
    if (prev_ev != NULL)
        fsm_fired_event = NULL;
    if (new_state == FSM_NO_CHANGE)
        new_state = cur_state;
    transition_func_t *transition = fsm_transition_table[cur_state][new_state];
    if (transition)
        transition(data);
    return new_state;
}

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    fsm_state_t cur_state = FSM_STATE_INIT;
    do {
        cur_state = fsm_run_state(cur_state, NULL);
        sleep(1);
    } while (1);
    return 0;
}
#endif
