/******************************************************************************
Finite State Machine
Project: assets/fsm.dot
Description: lcu_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2026-05-26 20:12:03 +0200
Generated from: assets/fsm.dot
The finite state machine has:
  5 states
  9 transition functions
******************************************************************************/

#include <syslog.h>
#include "fsm.h"

/*** USER CODE BEGIN MACROS ***/

/*** USER CODE END MACROS ***/

// GLOBALS
// State human-readable names
const char *state_names[] = { "init", "idle", "fatal", "flash", "update_light" };

// List of state functions
state_func_t *const state_table[NUM_STATES] = {
    do_init,         // in state init
    do_idle,         // in state idle
    do_fatal,        // in state fatal
    do_flash,        // in state flash
    do_update_light, // in state update_light
};

// Table of transition functions
transition_func_t *const transition_table[NUM_STATES][NUM_STATES] = {
    /* states:          init                 , idle                 , fatal                , flash                , update_light          */
    /* init         */ { NULL, init_to_idle, init_to_fatal, NULL, NULL },
    /* idle         */ { NULL, NULL, idle_to_fatal, idle_to_flash, idle_to_update_light },
    /* fatal        */ { NULL, NULL, NULL, NULL, NULL },
    /* flash        */ { NULL, flash_to_idle, flash_to_fatal, NULL, NULL },
    /* update_light */ { NULL, update_light_to_idle, update_light_to_fatal, NULL, NULL },
};

// Triggered event
event_data_t *fired_event = NULL;

/*** USER CODE BEGIN GLOBALS ***/

/*** USER CODE END GLOBALS ***/

// Function to check if an event has fired
bool is_event_triggered() {
    return fired_event != NULL;
}

// Function to trigger an event
void event_trigger(event_data_t *event) {
    if (fired_event != NULL)
        return;
    fired_event = event ? event : &(event_data_t){};
}

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: STATE_IDLE, STATE_FATAL
state_t do_init(state_data_t *data) {
    state_t next_state = STATE_IDLE;

    syslog(LOG_INFO, "[FSM] In state init");

    /*** USER CODE BEGIN DO_INIT ***/

    /*** USER CODE END DO_INIT ***/

    switch (next_state) {
        case STATE_IDLE:
        case STATE_FATAL:
            break;
        default:
            syslog(LOG_WARNING, "[FSM] Cannot pass from init to %s, remaining in this state", state_names[next_state]);
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_FLASH, STATE_IDLE, STATE_UPDATE_LIGHT, STATE_FATAL
state_t do_idle(state_data_t *data) {
    state_t next_state = NO_CHANGE;

    syslog(LOG_INFO, "[FSM] In state idle");

    /*** USER CODE BEGIN DO_IDLE ***/

    /*** USER CODE END DO_IDLE ***/

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_IDLE:
        case STATE_UPDATE_LIGHT:
        case STATE_FATAL:
            break;
        default:
            syslog(LOG_WARNING, "[FSM] Cannot pass from idle to %s, remaining in this state", state_names[next_state]);
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state fatal
// valid return states: NO_CHANGE, STATE_FLASH, STATE_FATAL
state_t do_fatal(state_data_t *data) {
    state_t next_state = NO_CHANGE;

    syslog(LOG_INFO, "[FSM] In state fatal");

    /*** USER CODE BEGIN DO_FATAL ***/

    /*** USER CODE END DO_FATAL ***/

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_FATAL:
            break;
        default:
            syslog(LOG_WARNING, "[FSM] Cannot pass from fatal to %s, remaining in this state", state_names[next_state]);
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: STATE_IDLE, STATE_FATAL
state_t do_flash(state_data_t *data) {
    state_t next_state = STATE_IDLE;

    syslog(LOG_INFO, "[FSM] In state flash");

    /*** USER CODE BEGIN DO_FLASH ***/

    /*** USER CODE END DO_FLASH ***/

    switch (next_state) {
        case STATE_IDLE:
        case STATE_FATAL:
            break;
        default:
            syslog(LOG_WARNING, "[FSM] Cannot pass from flash to %s, remaining in this state", state_names[next_state]);
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state update_light
// valid return states: NO_CHANGE, STATE_IDLE, STATE_UPDATE_LIGHT, STATE_FATAL
state_t do_update_light(state_data_t *data) {
    state_t next_state = NO_CHANGE;

    syslog(LOG_INFO, "[FSM] In state update_light");

    /*** USER CODE BEGIN DO_UPDATE_LIGHT ***/

    /*** USER CODE END DO_UPDATE_LIGHT ***/

    switch (next_state) {
        case NO_CHANGE:
        case STATE_IDLE:
        case STATE_UPDATE_LIGHT:
        case STATE_FATAL:
            break;
        default:
            syslog(LOG_WARNING, "[FSM] Cannot pass from update_light to %s, remaining in this state", state_names[next_state]);
            next_state = NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from init to idle
void init_to_idle(state_data_t *data) {
    syslog(LOG_INFO, "[FSM] State transition init_to_idle");

    /*** USER CODE BEGIN INIT_TO_IDLE ***/

    /*** USER CODE END INIT_TO_IDLE ***/
}

// This function is called in 1 transition:
// 1. from init to fatal
void init_to_fatal(state_data_t *data) {
    syslog(LOG_INFO, "[FSM] State transition init_to_fatal");

    /*** USER CODE BEGIN INIT_TO_FATAL ***/

    /*** USER CODE END INIT_TO_FATAL ***/
}

// This function is called in 1 transition:
// 1. from flash to idle
void flash_to_idle(state_data_t *data) {
    syslog(LOG_INFO, "[FSM] State transition flash_to_idle");

    /*** USER CODE BEGIN FLASH_TO_IDLE ***/

    /*** USER CODE END FLASH_TO_IDLE ***/
}

// This function is called in 1 transition:
// 1. from flash to fatal
void flash_to_fatal(state_data_t *data) {
    syslog(LOG_INFO, "[FSM] State transition flash_to_fatal");

    /*** USER CODE BEGIN FLASH_TO_FATAL ***/

    /*** USER CODE END FLASH_TO_FATAL ***/
}

// This function is called in 1 transition:
// 1. from idle to flash
void idle_to_flash(state_data_t *data) {
    syslog(LOG_INFO, "[FSM] State transition idle_to_flash");

    /*** USER CODE BEGIN IDLE_TO_FLASH ***/

    /*** USER CODE END IDLE_TO_FLASH ***/
}

// This function is called in 1 transition:
// 1. from idle to update_light
void idle_to_update_light(state_data_t *data) {
    syslog(LOG_INFO, "[FSM] State transition idle_to_update_light");

    /*** USER CODE BEGIN IDLE_TO_UPDATE_LIGHT ***/

    /*** USER CODE END IDLE_TO_UPDATE_LIGHT ***/
}

// This function is called in 1 transition:
// 1. from idle to fatal
void idle_to_fatal(state_data_t *data) {
    syslog(LOG_INFO, "[FSM] State transition idle_to_fatal");

    /*** USER CODE BEGIN IDLE_TO_FATAL ***/

    /*** USER CODE END IDLE_TO_FATAL ***/
}

// This function is called in 1 transition:
// 1. from update_light to idle
void update_light_to_idle(state_data_t *data) {
    syslog(LOG_INFO, "[FSM] State transition update_light_to_idle");

    /*** USER CODE BEGIN UPDATE_LIGHT_TO_IDLE ***/

    /*** USER CODE END UPDATE_LIGHT_TO_IDLE ***/
}

// This function is called in 1 transition:
// 1. from update_light to fatal
void update_light_to_fatal(state_data_t *data) {
    syslog(LOG_INFO, "[FSM] State transition update_light_to_fatal");

    /*** USER CODE BEGIN UPDATE_LIGHT_TO_FATAL ***/

    /*** USER CODE END UPDATE_LIGHT_TO_FATAL ***/
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

state_t run_state(state_t cur_state, state_data_t *data) {

    /*** USER CODE BEGIN RUN_STATE ***/

    /*** USER CODE END RUN_STATE ***/

    event_data_t *prev_ev = fired_event;
    state_t new_state = state_table[cur_state](data);
    // Reset event status
    if (prev_ev != NULL)
        fired_event = NULL;
    if (new_state == NO_CHANGE)
        new_state = cur_state;
    transition_func_t *transition = transition_table[cur_state][new_state];
    if (transition)
        transition(data);
    return new_state;
};

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    state_t cur_state = STATE_INIT;
    openlog("SM", LOG_PID | LOG_PERROR, LOG_USER);
    syslog(LOG_INFO, "Starting SM");
    do {
        cur_state = run_state(cur_state, NULL);
        sleep(1);
    } while (1);
    return 0;
}
#endif
