/******************************************************************************
Finite State Machine
Project: lcu-sw
Description: lcu_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2026-06-24 17:40:22 +0200
Generated from: assets/fsm.dot
The finite state machine has:
  4 states
  6 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#ifndef FSM_H
#define FSM_H
#include <stdlib.h>
#include <stdbool.h>

/*** USER CODE BEGIN MACROS ***/

/*** USER CODE END MACROS ***/

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
/*** USER STATE DATA TYPE BEGIN ***/
typedef struct {
    void (*brake_hw_update)(bool);
} fsm_state_data_t; //temp structure
/*** USER STATE DATA TYPE END ***/
// Event data object
// By default the struct is empty; put the data of the event inside
// the structure if you need or leave it empty
typedef struct {

    /*** USER CODE BEGIN EVENT_DATA ***/
    int dummy;
    /*** USER CODE END EVENT_DATA ***/

} fsm_event_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
    FSM_STATE_INIT = 0,
    FSM_STATE_IDLE,
    FSM_STATE_FATAL,
    FSM_STATE_FLASH,
    FSM_NUM_STATES,
    FSM_NO_CHANGE
} fsm_state_t;

// State human-readable names
extern const char *fsm_state_names[];

// State function and state transition prototypes
typedef fsm_state_t fsm_state_func_t(fsm_state_data_t *data);
typedef void transition_func_t(fsm_state_data_t *data);

/*** USER CODE BEGIN TYPES ***/

/*** USER CODE END TYPES ***/

// Functions to check and trigger an event
bool fsm_is_event_triggered();
void fsm_event_trigger(fsm_event_data_t *event);

// State functions

// Function to be executed in state init
// valid return states: FSM_STATE_IDLE, FSM_STATE_FATAL
fsm_state_t fsm_do_init(fsm_state_data_t *data);

// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_FLASH, FSM_STATE_IDLE, FSM_STATE_FATAL
fsm_state_t fsm_do_idle(fsm_state_data_t *data);

// Function to be executed in state fatal
// valid return states: FSM_NO_CHANGE, FSM_STATE_FLASH, FSM_STATE_FATAL
fsm_state_t fsm_do_fatal(fsm_state_data_t *data);

// Function to be executed in state flash
// valid return states: FSM_STATE_IDLE, FSM_STATE_FATAL
fsm_state_t fsm_do_flash(fsm_state_data_t *data);

// List of state functions
extern fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES];

// Transition functions
void fsm_init_to_idle(fsm_state_data_t *data);
void fsm_init_to_fatal(fsm_state_data_t *data);
void fsm_flash_to_idle(fsm_state_data_t *data);
void fsm_flash_to_fatal(fsm_state_data_t *data);
void fsm_idle_to_flash(fsm_state_data_t *data);
void fsm_idle_to_fatal(fsm_state_data_t *data);

// Table of transition functions
extern transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES];

// state manager
fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data);

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#endif
